AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM CloudFormation Template - Users, Groups, Roles, and Policies'

Resources:
  # IAM User
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'MischaCFN'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  # MyIAMGroup:
  MyIAMGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: 'MischaGroup'

  # Attach User to Group
  UserToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref MyIAMGroup
      Users:
        - !Ref MyIAMUser

  # IAM Role for EC2
  MyIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: ['ec2.amazonaws.com']
            Action: ['sts:AssumeRole']

  # S3 Custom Policy
  MyIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'CustomPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 's3:GetObject'
            Resource: '*'
      Roles:
        - !Ref MyIAMRole