AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC CloudFormation Template - Week 5 Exercise'

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CloudFormation-VPC
        - Key: Environment
          Value: Learning
        - Key: Project
          Value: CloudAcademy-Week5